security:
    encoders:
#        Drosera\UserBundle\Entity\User: plaintext
        Drosera\UserBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: true
            iterations: 5000

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        drosera_userbundle:
            id: drosera_user.user_manager
            #entity: { class: Drosera\UserBundle\Entity\User, property: username }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
                default_target_path: /admin
            logout:
                path:   /logout
                target: /
            
    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/admin, roles: ROLE_ADMIN, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        
    #acl:
    #    connection: default
