drosera_user_admin_user_list:
    pattern:  /list
    defaults: { _controller: DroseraUserBundle:User:list }
    
drosera_user_admin_user_create:
    pattern:  /create
    defaults: { _controller: DroseraUserBundle:User:create }
    
drosera_user_admin_user_edit:
    pattern:  /edit/{id}
    defaults: { _controller: DroseraUserBundle:User:edit }
    
drosera_user_admin_user_delete:
    pattern:  /delete/{id}
    defaults: { _controller: DroseraUserBundle:User:delete }

drosera_user_admin_user_index:
    pattern:  /
    defaults: { _controller: DroseraUserBundle:User:list }
