services:
    # parent service pro DI repositaru
    drosera_admin.repo:
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        class:           Doctrine\ORM\EntityRepository
        abstract:        true
