drosera_user_security:
    resource: "@DroseraUserBundle/Resources/config/routing/security.yml"
    
drosera_user_user:
    resource: "@DroseraUserBundle/Resources/config/routing/user.yml"
    prefix:   /users

drosera_user_user_group:
    resource: "@DroseraUserBundle/Resources/config/routing/user_group.yml"
    prefix:   /user-groups
