parameters: 
    stof.entity.log_entry.class: Stof\DoctrineExtensionsBundle\Entity\LogEntry # presunout mimo UserBundle
    drosera_user.entity.user.class: Drosera\UserBundle\Entity\User
    drosera_user.entity.user_group.class: Drosera\UserBundle\Entity\UserGroup
    drosera_user.entity.credential.class: Drosera\UserBundle\Entity\Credential
    drosera_user.manager.user_group_manager.class: Drosera\UserBundle\Manager\UserGroupManager
    drosera_user.manager.user_manager.class: Drosera\UserBundle\Manager\UserManager
    drosera_user.manager.credential_manager.class: Drosera\UserBundle\Manager\CredentialManager 
    drosera_user.validator.unique.class: Drosera\UserBundle\Validator\UniqueValidator

services: 
    # presunout mimo UserBundle
    stof.repository.log_entry_repository:
        parent: drosera_admin.repo
        arguments: [%stof.entity.log_entry.class%]
  
    drosera_user.repository.user_repository:
        parent: drosera_admin.repo
        arguments: [%drosera_user.entity.user.class%]
        
    drosera_user.repository.user_group_repository:
        parent: drosera_admin.repo
        arguments: [%drosera_user.entity.user_group.class%]
        
    drosera_user.repository.credential_repository:
        parent: drosera_admin.repo
        arguments: [%drosera_user.entity.credential.class%]

    drosera_user.user_manager:
        class: %drosera_user.manager.user_manager.class%
        arguments: [@drosera_user.repository.user_repository, @service_container, @security.encoder_factory, %drosera_user.entity.user.class%]
    
    drosera_user.user_group_manager:
        class: %drosera_user.manager.user_group_manager.class%
        arguments: [@drosera_user.repository.user_group_repository, @stof.repository.log_entry_repository, @service_container, %drosera_user.entity.user_group.class%]   

    drosera_user.credential_manager:
        class: %drosera_user.manager.credential_manager.class%
        arguments: [@drosera_user.repository.credential_repository]

    drosera_user.validator.unique:
        class:      %drosera_user.validator.unique.class%
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: validator.constraint_validator, alias: drosera_user.validator.unique }